Bump required python version to 3.9
Summary:
Attempt to run unit tests with python 3.8 (ondemand default) fails with:

ImportError: PyO3 modules compiled for CPython 3.8 or older may only be initialized once per interpreter process

PyO3 [1] seems to be a transitive dependency.

The easiest way to fix this is to upgrade underlying python.

[1] https://pyo3.rs/v0.24.2/getting-started.html

Reviewed By: danielocfb, anakryiko

Differential Revision: D74443235

fbshipit-source-id: 2577b78d8b6fb3452af9040b6cbc74101e6f7103